apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- ../../base/cilium
- bgp.yaml
- cilium-node-config/kube-vm1.yaml
patchesStrategicMerge:
- release.yaml
configMapGenerator:
- name: cilium-values-cluster2
  files:
  - values.yaml=values.yaml
